// Frontend/student-portal-angular/src/app/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: false,
  templateUrl: './course-card.component.html',
  styleUrls: ['./course-card.component.css']
})
export class CourseCardComponent {
  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';
}

<article class="course-card">
  <h3>{{ name }}</h3>
  <p>{{ code }}</p>
  <span class="credits">{{ credits }} credits</span>
  <span class="grade">Grade: {{ grade }}</span>
</article>

// Frontend/handson10/react/student-portal-react/src/components/CourseCard.jsx
function CourseCard({ name, code, credits, grade, hideButton = false }) {
  return (
    <article className="course-card">
      <h3>{name}</h3>
      <p>{code}</p>
      <span className="credits">{credits} credits</span>
      <span className="grade">Grade: {grade}</span>
      {!hideButton && (
        <button type="button" className="enroll-btn-inline">Enroll</button>
      )}
    </article>
  );
}

export default CourseCard;
