// Frontend/handson5/student-portal-react/src/components/StudentProfile.jsx
import { useState } from 'react';

function StudentProfile() {
  const [profile, setProfile] = useState({
    name: '',
    email: '',
    semester: ''
  });

  function handleChange(e) {
    const { name, value } = e.target;
    setProfile((prev) => ({ ...prev, [name]: value }));
  }

  return (
    <section id="profile" className="profile-section">
      <h2>Student Profile</h2>
      <form>
        <label>
          Name
          <input
            type="text"
            name="name"
            value={profile.name}
            onChange={handleChange}
            placeholder="Your name"
          />
        </label>

        <label>
          Email
          <input
            type="email"
            name="email"
            value={profile.email}
            onChange={handleChange}
            placeholder="you@example.com"
          />
        </label>

        <label>
          Semester
          <input
            type="number"
            name="semester"
            value={profile.semester}
            onChange={handleChange}
            placeholder="e.g. 6"
            min="1"
            max="8"
          />
        </label>
      </form>

      <div className="profile-preview">
        <p><strong>Name:</strong> {profile.name || '—'}</p>
        <p><strong>Email:</strong> {profile.email || '—'}</p>
        <p><strong>Semester:</strong> {profile.semester || '—'}</p>
      </div>
    </section>
  );
}

export default StudentProfile;

// Frontend/student-portal-angular/src/app/student-profile/student-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-student-profile',
  standalone: false,
  templateUrl: './student-profile.component.html',
  styleUrls: ['./student-profile.component.css']
})
export class StudentProfileComponent implements OnInit {
  profileForm!: FormGroup;

  ngOnInit(): void {
    this.profileForm = new FormGroup({
      name: new FormControl('', [Validators.required]),
      email: new FormControl('', [Validators.required, Validators.email]),
      semester: new FormControl('', [
        Validators.required,
        Validators.min(1),
        Validators.max(8)
      ])
    });
  }

  get name() {
    return this.profileForm.get('name');
  }

  get email() {
    return this.profileForm.get('email');
  }

  get semester() {
    return this.profileForm.get('semester');
  }

  onSubmit(): void {
    console.log(this.profileForm.value);
  }
}

<section class="profile-section">
	<h2>Student Profile</h2>

	<form [formGroup]="profileForm" (ngSubmit)="onSubmit()">
		<label>
			Name
			<input type="text" formControlName="name" placeholder="Your name" />
			<span class="field-error" *ngIf="name?.touched && name?.invalid">
				Name is required
			</span>
		</label>

		<label>
			Email
			<input type="email" formControlName="email" placeholder="you@example.com" />
			<span class="field-error" *ngIf="email?.touched && email?.invalid">
				Enter a valid email
			</span>
		</label>

		<label>
			Semester
			<input type="number" formControlName="semester" placeholder="e.g. 6" />
			<span class="field-error" *ngIf="semester?.touched && semester?.invalid">
				Semester must be between 1 and 8
			</span>
		</label>

		<button type="submit" [disabled]="profileForm.invalid">Submit</button>
	</form>
</section>
